# General settings
title: Mechanics at BSc Civil Engineering
author:  Tom van Woudenberg from Delft University of Technology, built with <a href="https://teachbooks.tudelft.nl/">TeachBooks</a> and <a href="https://jupyterbook.org/">Jupyter Book</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="license noopener noreferrer"">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt=""></a>
email: T.R.vanWoudenberg@tudelft.nl

execute:
  execute_notebooks: "off"

only_build_toc_files: true

html:
  favicon : "images/favicon.ico"
  baseurl :  "https://oit.tudelft.nl/CEG-mechanics-BSc/"
  home_page_in_navbar       : true

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/**"]
    html_theme_options:
      repository_url: "https://github.com/TUDelft-books/CEG-mechanics-BSc/"
      path_to_docs: "book"
      repository_branch: "main"
      use_repository_button: true
      use_edit_page_button: true
      use_issues_button : true
      announcement : "This version of the book (url has /2025-assignment3), only includes the chapters relevant for the third assignment of 2025. It will be deleted in May 2026. For the full book, please visit the <a href='http://oit.tudelft.nl/CEG-mechanics-BSc/' style='color:white'>full version of the book</a>."
      launch_buttons:
        thebe: true
      logo:
        text: "Assignment 3 CT1000 Structural Mechanics 2025/2026"
    html_show_copyright: false
    html_last_updated_fmt: '%B %-d, %Y'
    bibtex_default_style: myapastyle
    bibtex_reference_style: author_year_round
    mathjax3_config:
      chtml: {
        mtextInheritFont: true # To typeset text within math prettier
      }
  local_extensions:
    apastyle: _ext/
    bracket_citation_style: _ext/
  extra_extensions:
    - sphinx.ext.imgconverter
    - jupyterbook_patches
    - download_link_replacer
    - sphinx.ext.extlinks
    - sphinx_image_inverter
    - sphinx_exercise
    - sphinx_tudelft_theme

bibtex_bibfiles: 
  - references.bib

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - html_image
    - linkify
    - substitution
    - tasklist
